[pytest]
pythonpath = .
addopts = -p no:warnings -W ignore::urllib3.exceptions.NotOpenSSLWarning -W ignore:.*LibreSSL.*:Warning
filterwarnings =
    ignore::urllib3.exceptions.NotOpenSSLWarning
    ignore:.*LibreSSL.*:Warning
