#!/usr/bin/env python3
"""PB-017 local governance action tracking.

PB-017 tracks execution and completion state for governance improvement
actions generated by PB-016. It is local-only and performs no AWS,
PostgreSQL, TSA, external network, or external certification-provider calls.
"""

from __future__ import annotations

import argparse
import json
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any


PLAN = "pb016_governance_improvement_plan.json"
ROADMAP = "pb016_governance_roadmap.json"
ACTION_REGISTER = "pb016_governance_action_register.json"
PRIORITY_MATRIX = "pb016_governance_priority_matrix.json"
TRACKER = "pb017_governance_action_tracker.json"
PROGRESS = "pb017_governance_progress_report.json"
COMPLETION = "pb017_governance_completion_report.json"
DASHBOARD = "pb017_governance_status_dashboard.json"
TRACKER_SCHEMA = "usbay.pb017.governance_action_tracker.v1"
PROGRESS_SCHEMA = "usbay.pb017.governance_progress_report.v1"
COMPLETION_SCHEMA = "usbay.pb017.governance_completion_report.v1"
DASHBOARD_SCHEMA = "usbay.pb017.governance_status_dashboard.v1"
ALLOWED_INPUTS = {PLAN, ROADMAP, ACTION_REGISTER, PRIORITY_MATRIX}
REQUIRED_INPUTS = {PLAN, ROADMAP, ACTION_REGISTER}
ALLOWED_STATUSES = {"OPEN", "IN_PROGRESS", "BLOCKED", "COMPLETED", "CANCELLED"}
ACTIVE_STATUSES = {"OPEN", "IN_PROGRESS", "BLOCKED"}


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def today() -> date:
    return datetime.now(timezone.utc).date()


def load_json(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"{path.name}:JSON_INVALID:{exc.msg}") from exc
    if not isinstance(payload, dict):
        raise ValueError(f"{path.name}:JSON_OBJECT_REQUIRED")
    return payload


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def parse_due_date(value: Any) -> date | None:
    if not isinstance(value, str) or not value:
        return None
    try:
        return date.fromisoformat(value)
    except ValueError:
        return None


def load_inputs(input_dir: Path) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any], list[str]]:
    errors: list[str] = []
    if not input_dir.is_dir():
        return {}, {}, {}, [f"PB017_INPUT_DIR_MISSING:{input_dir}"]
    present = {path.name for path in input_dir.iterdir() if path.is_file()}
    for filename in sorted(REQUIRED_INPUTS - present):
        if filename == PLAN:
            errors.append("PB017_IMPROVEMENT_PLAN_MISSING")
        elif filename == ROADMAP:
            errors.append("PB017_ROADMAP_MISSING")
        elif filename == ACTION_REGISTER:
            errors.append("PB017_ACTION_REGISTER_MISSING")
    for filename in sorted(present - ALLOWED_INPUTS):
        errors.append(f"PB017_UNSUPPORTED_GOVERNANCE_ARTIFACT:{filename}")

    payloads: dict[str, dict[str, Any]] = {}
    for filename in sorted(ALLOWED_INPUTS & present):
        try:
            payloads[filename] = load_json(input_dir / filename)
        except Exception as exc:
            errors.append(f"PB017_INPUT_INVALID:{filename}:{exc}")
    return payloads.get(PLAN, {}), payloads.get(ROADMAP, {}), payloads.get(ACTION_REGISTER, {}), errors


def evaluate(input_dir: Path) -> tuple[list[str], dict[str, Any]]:
    plan, roadmap, action_register, errors = load_inputs(input_dir)
    if plan and plan.get("schema") != "usbay.pb016.governance_improvement_plan.v1":
        errors.append("PB017_IMPROVEMENT_PLAN_SCHEMA_INVALID")
    if roadmap and roadmap.get("schema") != "usbay.pb016.governance_roadmap.v1":
        errors.append("PB017_ROADMAP_SCHEMA_INVALID")
    if action_register and action_register.get("schema") != "usbay.pb016.governance_action_register.v1":
        errors.append("PB017_ACTION_REGISTER_SCHEMA_INVALID")

    actions = action_register.get("actions", [])
    if action_register and not isinstance(actions, list):
        errors.append("PB017_ACTION_REGISTER_INVALID")
        actions = []
    roadmap_items = roadmap.get("roadmap", [])
    if roadmap and not isinstance(roadmap_items, list):
        errors.append("PB017_ROADMAP_INVALID")
        roadmap_items = []

    normalized_actions: list[dict[str, Any]] = []
    open_actions = completed_actions = blocked_actions = overdue_actions = 0
    today_value = today()
    for index, action in enumerate(actions, start=1):
        if not isinstance(action, dict):
            errors.append(f"PB017_ACTION_INVALID:ACTION-{index:03d}")
            continue
        action_id = str(action.get("action_id", f"ACTION-{index:03d}"))
        status = str(action.get("status", "OPEN")).upper()
        severity = str(action.get("severity", "MEDIUM")).upper()
        if status not in ALLOWED_STATUSES:
            errors.append(f"PB017_INVALID_ACTION_STATUS:{action_id}:{status}")
        due_date = parse_due_date(action.get("due_date"))
        due_date_invalid = action.get("due_date") not in (None, "") and due_date is None
        if due_date_invalid:
            errors.append(f"PB017_INVALID_DUE_DATE:{action_id}")
        overdue = bool(due_date and due_date < today_value and status in ACTIVE_STATUSES)
        if overdue:
            overdue_actions += 1
            if severity == "CRITICAL":
                errors.append(f"PB017_OVERDUE_CRITICAL_ACTION:{action_id}")
        if status == "COMPLETED":
            completed_actions += 1
        elif status == "BLOCKED":
            blocked_actions += 1
        elif status in {"OPEN", "IN_PROGRESS"}:
            open_actions += 1
        normalized_actions.append(
            {
                "action_id": action_id,
                "priority_id": str(action.get("priority_id", "Information not provided")),
                "title": str(action.get("title", "Information not provided")),
                "severity": severity,
                "status": status,
                "due_date": action.get("due_date"),
                "overdue": overdue,
                "owner": str(action.get("owner", "Information not provided")),
                "required_evidence": str(action.get("required_evidence", "Information not provided")),
            }
        )

    total_actions = len(normalized_actions)
    progress_percentage = round((completed_actions / total_actions) * 100, 2) if total_actions else 0.0
    total_phases = len(roadmap_items)
    completed_phase_count = 0
    for phase in roadmap_items:
        if not isinstance(phase, dict):
            continue
        priority_items = phase.get("priority_items", [])
        if not priority_items:
            continue
        related = [action for action in normalized_actions if action.get("priority_id") in priority_items]
        if related and all(action["status"] == "COMPLETED" for action in related):
            completed_phase_count += 1
    roadmap_completion_percentage = round((completed_phase_count / total_phases) * 100, 2) if total_phases else 0.0

    context = {
        "actions": normalized_actions,
        "total_actions": total_actions,
        "open_actions": open_actions,
        "completed_actions": completed_actions,
        "blocked_actions": blocked_actions,
        "overdue_actions": overdue_actions,
        "progress_percentage": progress_percentage,
        "roadmap_completion_percentage": roadmap_completion_percentage,
        "pb016_decision": plan.get("decision"),
    }
    return sorted(dict.fromkeys(errors)), context


def write_outputs(output_dir: Path, errors: list[str], context: dict[str, Any]) -> None:
    generated_at = utc_now()
    decision = "VERIFIED" if not errors else "BLOCKED"
    common = {
        "generated_at": generated_at,
        "decision": decision,
        "fail_closed": bool(errors),
        "errors": errors,
        "local_governance_tracking_only": True,
        "no_external_certification_claim": True,
        "no_regulatory_certification_claim": True,
        "no_legal_compliance_certification_claim": True,
        "no_production_readiness_claim": True,
        "aws_access_performed": False,
        "postgresql_access_performed": False,
        "tsa_access_performed": False,
        "external_network_access_performed": False,
    }
    write_json(
        output_dir / TRACKER,
        {
            "schema": TRACKER_SCHEMA,
            **common,
            "actions": context["actions"],
            "total_actions": context["total_actions"],
            "open_actions": context["open_actions"],
            "completed_actions": context["completed_actions"],
            "blocked_actions": context["blocked_actions"],
            "overdue_actions": context["overdue_actions"],
        },
    )
    write_json(
        output_dir / PROGRESS,
        {
            "schema": PROGRESS_SCHEMA,
            **common,
            "governance_progress_percentage": context["progress_percentage"],
            "roadmap_completion_percentage": context["roadmap_completion_percentage"],
            "open_actions": context["open_actions"],
            "completed_actions": context["completed_actions"],
            "blocked_actions": context["blocked_actions"],
        },
    )
    write_json(
        output_dir / COMPLETION,
        {
            "schema": COMPLETION_SCHEMA,
            **common,
            "completed_actions": [
                action for action in context["actions"] if action["status"] == "COMPLETED"
            ],
            "completed_action_count": context["completed_actions"],
            "total_actions": context["total_actions"],
        },
    )
    write_json(
        output_dir / DASHBOARD,
        {
            "schema": DASHBOARD_SCHEMA,
            **common,
            "status": "ON_TRACK" if not errors else "BLOCKED",
            "pb016_decision": context.get("pb016_decision"),
            "governance_progress_percentage": context["progress_percentage"],
            "roadmap_completion_percentage": context["roadmap_completion_percentage"],
            "open_actions": context["open_actions"],
            "completed_actions": context["completed_actions"],
            "blocked_actions": context["blocked_actions"],
            "overdue_actions": context["overdue_actions"],
            "overdue_critical_action_detected": any("OVERDUE_CRITICAL_ACTION" in error for error in errors),
        },
    )


def track(input_dir: Path, output_dir: Path) -> list[str]:
    errors, context = evaluate(input_dir)
    write_outputs(output_dir, errors, context)
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description="PB-017 local governance action tracking.")
    parser.add_argument("pb016_input_dir")
    parser.add_argument("output_dir")
    args = parser.parse_args()
    errors = track(Path(args.pb016_input_dir).resolve(), Path(args.output_dir).resolve())
    if errors:
        print("Decision: BLOCKED")
        for error in errors:
            print(error)
        return 1
    print("Decision: VERIFIED")
    print("PB017_GOVERNANCE_ACTION_TRACKING_VERIFIED")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
